spring:
  application:
    name: Eureka-Server

  cloud:
    config:
      uri: http://localhost:8084
      username: root
      password: root

#eureka:
  #client:
    #registerWithEureka: false
    #fetchRegistry: false
#server:
  #port: 8761