server:
  port: 8082

spring:
  application:
    name: 2.credits
  cloud:
    config:
      uri: http://localhost:8084
      username: root
      password: root

#server:
  #port: 8082

#spring:
  #application:
    #name: Credits-Client
  #data:
    #mongodb:
      #uri: mongodb://localhost:27017/credits