server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: 1.account
          uri: http://localhost:8081/
          predicates:
            - Path=/Bootcamp/ProyectoV2.0/1.Account/**
        - id: 2.credits
          uri: http://localhost:8082/
          predicates:
            - Path=/Bootcamp/ProyectoV2.0/2.Credits/**
        - id: 3.customer
          uri: http://localhost:8083/
          predicates:
            - Path=/Bootcamp/ProyectoV2.0/3.Customer/**